=== sh4hids/shahid.pro/.astro/collections/projects.schema.json
{
  "$ref": "#/definitions/projects",
  "definitions": {
    "projects": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "url": {
          "type": "string",
          "format": "uri"
        },
        "isPublished": {
          "type": "boolean",
          "default": false
        },
        "github": {
          "type": "string",
          "format": "uri"
        },
        "createdAt": {
          "type": "string"
        },
        "updatedAt": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "description",
        "url",
        "createdAt",
        "updatedAt"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== sh4hids/shahid.pro/src/content/projects/book-manager.json
{
    "name": "book-manager",
    "description": "A simple library management app built with Electron, NeDB and React.",
    "url": "https://github.com/bdTechies/book-manager",
    "github": "https://github.com/bdTechies/book-manager",
    "createdAt": "2023-11-02T01:11:23.742Z",
    "updatedAt": "2023-11-02T01:11:23.742Z",
    "isPublished": true
}

=== sh4hids/shahid.pro/src/content/projects/dam-janun.json
{
    "name": "dam-janun",
    "description": "A react project to show prices of the same book in different shops in Bangladesh.",
    "url": "https://github.com/sh4hids/dam-janun",
    "github": "https://github.com/sh4hids/dam-janun",
    "createdAt": "2024-05-15T15:17:25.091Z",
    "updatedAt": "2024-05-15T15:17:25.091Z",
    "isPublished": true
}

=== sh4hids/shahid.pro/src/content/projects/roshui-pronali.json
{
    "name": "roshui-pronali",
    "description": "A Bnagla recipe website built with Astro, React, and TailwindCSS",
    "url": "https://roshuipronali.shahid.pro/",
    "github": "https://github.com/sh4hids/roshui-pronali",
    "createdAt": "2023-11-02T01:11:23.742Z",
    "updatedAt": "2023-11-02T01:11:23.742Z",
    "isPublished": true
}

=== sh4hids/shahid.pro/src/content/projects/theme-open-sourcerer.json
{
    "name": "gatsby-theme-open-sourcerer",
    "description": "A configurable minimal gatsby portfolio theme for open source developers.",
    "url": "https://gatsby-theme-open-sourcerer.netlify.app/",
    "github": "https://github.com/sh4hids/gatsby-theme-open-sourcerer",
    "createdAt": "2024-05-15T15:12:18.875Z",
    "updatedAt": "2024-05-15T15:12:18.875Z",
    "isPublished": true
}

=== sh4hids/shahid.pro/src/content/projects/bangla-calendar.json
{
    "name": "bangla-calendar",
    "description": "A small JavaScript library to convert any valid JavaScript date to Bangla date.",
    "url": "https://github.com/sh4hids/bangla-calendar",
    "github": "https://github.com/sh4hids/bangla-calendar",
    "createdAt": "2023-11-02T01:11:23.742Z",
    "updatedAt": "2023-11-02T01:11:23.742Z",
    "isPublished": true
}

=== sh4hids/shahid.pro/src/content/projects/prayertiming-cli.json
{
    "name": "prayertiming-cli",
    "description": "A command line tool to show Muslim prayer times based on coordinates.",
    "url": "https://github.com/sh4hids/prayertiming-cli",
    "github": "https://github.com/sh4hids/prayertiming-cli",
    "createdAt": "2024-05-15T15:11:07.146Z",
    "updatedAt": "2024-05-15T15:11:07.146Z",
    "isPublished": true
}

=== sh4hids/shahid.pro/src/content/projects/deskaide.json
{
    "name": "deskaide",
    "description": "An electron based desktop application to help managing pc usage.",
    "url": "https://github.com/deskaide/deskaide",
    "github": "https://github.com/deskaide/deskaide",
    "isPublished": true,
    "createdAt": "2023-11-02T01:11:23.742Z",
    "updatedAt": "2023-11-02T01:11:23.742Z"
}

=== sh4hids/shahid.pro/src/content/projects/prozuktischool.json
{
    "name": "prozuktischool.com",
    "description": "An open source bangla community blog site build with Gatsby and Styled Components.",
    "url": "https://prozuktischool.com",
    "github": "https://github.com/prozuktischool/prozuktischool.com",
    "createdAt": "2023-11-02T01:11:23.742Z",
    "updatedAt": "2023-11-02T01:11:23.742Z",
    "isPublished": true
}
